---
- hosts: localhost
  become: yes
  vars:
    - src_dir: src
    - work_dir: work

  tasks:
    - name: install httpd 
      yum: name=httpd state=latest
    - name: install httpd-devel
      yum: name=httpd-devel state=latest
    - name: start httpd and enabled
      service: name=httpd state=started enabled=yes
    - name: change owner
      file: dest=/var/www/html owner=vagrant recurse=yes

  handlers:
